#DEPLOY_TARGET
#DEPLOY_RUNUSER_DIRS
DEPLOY_TARGET_PORT ?= 22
DEPLOY_TARGET_DIR ?= /
DEPLOY_TARGET_USER ?= root
DEPLOY_RUNUSER ?= $(DEPLOY_TARGET_USER)
DEPLOY_IDENTITY_FILE ?= $$HOME/.ssh/id_rsa
DEPLOY_RELNAME_AND_VERSION := $(shell erl -noshell -eval '{ok,Commands}=file:consult("$(CURDIR)/relx.config"), {release,{Relname, Relversion},_}=lists:keyfind(release,1,Commands), io:format("~p "++Relversion++"~n",[Relname]), halt().')
DEPLOY_RELNAME := $(firstword $(DEPLOY_RELNAME_AND_VERSION))
space := $(subst ,, )
DEPLOY_TARBALLNAME := $(subst $(space),-,$(DEPLOY_RELNAME_AND_VERSION)).tar.gz
DEPLOY_COPY_COMMAND := scp -P $(DEPLOY_TARGET_PORT) -i $(DEPLOY_IDENTITY_FILE) $(RELX_OUTPUT_DIR)/$(DEPLOY_RELNAME)/$(DEPLOY_TARBALLNAME) $(DEPLOY_TARGET_USER)@$(DEPLOY_TARGET):$(DEPLOY_TARGET_DIR)
DEPLOY_SSH := ssh -p $(DEPLOY_TARGET_PORT) -i $(DEPLOY_IDENTITY_FILE) $(DEPLOY_TARGET_USER)@$(DEPLOY_TARGET)
DEPLOY_EXTRACT_COMMAND := $(DEPLOY_SSH) "mkdir -p $(DEPLOY_TARGET_DIR)/$(DEPLOY_RELNAME) && tar xzf $(DEPLOY_TARGET_DIR)/$(DEPLOY_TARBALLNAME) -C $(DEPLOY_TARGET_DIR)/$(DEPLOY_RELNAME)"
DEPLOY_PROVIDE_RUNUSER := $(DEPLOY_SSH) "cat /etc/passwd | grep $(DEPLOY_RUNUSER) || useradd $(DEPLOY_RUNUSER) -M -s /bin/false"
DEPLOY_RUN_COMMAND := $(DEPLOY_SSH) "sh -s $$SHELL -c '$(DEPLOY_TARGET_DIR)/$(DEPLOY_RELNAME)/bin/$(DEPLOY_RELNAME) start' $(DEPLOY_RUNUSER)"

deploy: rel
ifeq ($(DEPLOY_TARGET),)
	$(error Error: must supply a deploy target via DEPLOY_TARGET variable)
endif
	$(RELX) tar
	$(DEPLOY_COPY_COMMAND)
	$(DEPLOY_EXTRACT_COMMAND)
	$(DEPLOY_PROVIDE_RUNUSER)
	$(DEPLOY_RUN_COMMAND)
